### ISSUE TITLE
Furnaces don't drop

### ISSUE THREAD

**Issue by BatJPJonyGod** [pnk2u/More-Smoker-Variants#1]
On Minecraft 1.21 fabric, when i have More Smoker Variants as well as More Furnaces Variants, the smokers can be mined and drop as normal but the deepslate furnace and blackstone furnace take forever to mine and don't drop. I don't think there's supposed to be incompatibility between the two since more furnace is required for the deepsltae smoker.

**Comment by pnk2u** [comment]
Thanks for reporting this. It was caused by a bug fix that fortunately is no longer needed and as such I removed the offending files in version 1.1.1 that was just released. Let me know if there's anything else and thanks again. (:
